### ISSUE TITLE
This reCAPTCHA is currently running on localhost

### ISSUE THREAD

**Issue by switchkiller** [TrailBlazerZ/recaptcha-php#1]
I am trying to run it on my localhost. The captcha is validating every time the Turing test begins.

**Comment by r34ctor** [comment]
There is a "," missing just after the array ending bracket. 
curl_setopt_array($curl, [
	CURLOPT_RETURNTRANSFER => 1,
	CURLOPT_URL => 'https://www.google.com/recaptcha/api/siteverify',
	CURLOPT_POST => 1,
	CURLOPT_POSTFIELDS => [
		'secret' => '6LfFYxwTAAAAALkP7btrWNo61nPl4Ia1-3nBN2vK',
		'response' => $_POST['g-recaptcha-response'],
           ** ],**
]);

**Comment by ghost** [comment]
Because it is under development, it will always appear on localhost.
